services:
  mysql-container:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: Bjit@1234567
    ports:
      - "3307:3306"
    volumes:
      - ./ecommerce/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ecommerce-network
    hostname: mysql-host-productsmicroservice

  products-microservice:
    image: amitmondol/ecommerce-products-microservice:v1.2
    environment:
      MYSQL_HOST: mysql-host-productsmicroservice
      MYSQL_PASSWORD: Bjit@1234567
    ports:
      - "8081:8080"
    networks:
      - ecommerce-network
    depends_on:
      - mysql-container

  postgres-container:
     image: postgres:18.1
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=Bjit@1234567
       - POSTGRES_DB=eCommerceUsers
     ports:
        - "5432:5432"
     volumes: 
        - ./ecommerce/postgres-init:/docker-entrypoint-initdb.d
     networks:
        - ecommerce-network

  users-microservice:
    image: amitmondol/ecommerce-users-microservice:1.0
    environment:
      POSTGRES_HOST: postgres-container
      POSTGRES_PASSWORD: Bjit@1234567
    ports:
      - "9090:9090"
    networks:
      - ecommerce-network
    depends_on: 
        -  postgres-container

networks:
  ecommerce-network:
    driver: bridge
